spring:
  jpa:
    hibernate:
      show_sql: true
      #      ddl-auto: validate
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ideas4transfer
    username: postgres
    password: n7g2phk2
logging:
  level:
    org:
      hibernate:
        type: trace